<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-27 at 22:17:17.
 */
class afTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var af
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new af;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers af::boot
     * @todo   Implement testBoot().
     */
    public function testBoot()
    {
        $this->assertEquals(\af::$app_dir, __DIR__.'/../mock', 'app_dir');
        $this->assertEquals(\af::$fwk_dir, dirname(__DIR__), 'fwk_dir');        
        //$this->assertContains(array('af', 'autoload'), spl_autoload_functions(), 'autoload');
    }

    /**
     * @covers af::autoload
     * @todo   Implement testAutoload().
     */
    public function testAutoload()
    {
        $this->assertTrue($class = class_exists('af\node'), '\af\node');
        
        $afnode = new \af\node;
        $this->assertInstanceOf('af\node', $afnode);
        
        $this->assertTrue($class = class_exists('app'), '\app');        
        
        $this->assertTrue($class = class_exists('node'), '\node');
        
        $this->assertFalse($class = class_exists('notexists'), '\node');
        
        $this->assertTrue($class = class_exists('af\app\header'), '\af\app\header');  
        
        $this->assertTrue($class = class_exists('app\header'), '\app\header'); 
        
        $this->assertTrue($class = class_exists('mailer'), '\af\mailer'); 
        
        $node   =   new \node;
        $this->assertInstanceOf('\node', $node);
        $this->assertInstanceOf('\af\node', $node);
    }

}
